#include "xutil.h"

#include <QStringList>
#include <QString>
#include <QMap>

static const QString s_ContryGmtTimezone =
"(AU&8):Australia/Perth,"
"(AU&9):Australia/Adelaide,"
"(AU&10):Australia/Sydney,"
"(BR&-5):America/Porto&Velho,"
"(BR&-4):America/Sao&Paulo,"
"(BR&-3):America/Fortaleza,"
"(CA&-9):America/Dawson,"
"(CA&-8):America/Vancouver,"
"(CA&-7):America/Regina,"
"(CA&-6):America/Winnipeg,"
"(CA&-5):America/Montreal,"
"(CA&-4):America/St&Johns,"
"(CN&5):Asia/Kashgar,"
"(CN&7):Asia/Chongqing,"
"(CN&8):Asia/Shanghai,"
"(MX&-8):America/Tijuana,"
"(MX&-7):America/Mexico&City,"
"(MX&-6):America/Cancun,"
"(MY&6):Asia/Kuala&Lumpur,"
"(MY&7):Asia/Kuching,"
"(NZ&11):Pacific/Auckland,"
"(NZ&12):Pacific/Chatham,"
"(RU&1):Europe/Kaliningrad,"
"(RU&2):Europe/Moscow,"
"(RU&3):Europe/Samara,"
"(RU&4):Asia/Omsk,"
"(RU&5):Asia/Novosibirsk,"
"(RU&6):Asia/Irkutsk,"
"(RU&8):Asia/Vladivostok,"
"(RU&9):Asia/Sakhalin,"
"(RU&10):Asia/Kamchatka,"
"(RU&11):Asia/Anadyr,"
"(US&-11):America/Adak,"
"(US&-10):America/Anchorage,"
"(US&-9):America/Yakutat,"
"(US&-8):America/Los&Angeles,"
"(US&-7):America/Denver,"
"(US&-6):America/Chicago,"
"(US&-5):America/New&York,"
"(US&-3):America/North&Dakota/Center";


static QString s_GmtTimezone =
"-12:Pacific/Pago_Pago,"
"-11:Pacific/Honolulu,"
"-10:Pacific/Tahiti,"
"-9:America/Dawson,"
"-8:America/Los_Angeles,"
"-7:America/Mexico_City,"
"-6:America/Chicago,"
"-5:America/New_York,"
"-4:America/Argentina/Buenos_Aires,"
"-3:America/Bahia,"
"-2:Atlantic/Reykjavik,"
"-1:Europe/Dublin,"
"0:Europe/London,"
"1:Europe/Rome,"
"2:Africa/Cairo,"
"3:Asia/Riyadh,"
"4:Asia/Kabul,"
"5:Asia/Calcutta,"
"6:Asia/Singapore,"
"7:Asia/Hong_Kong,"
"8:Asia/Shanghai,"
"9:Asia/Tokyo,"
"10:Australia/Sydney,"
"11:Pacific/Auckland,"
"12:Pacific/Chatham";

static const QString s_CountryTimezone =
"AD:Europe/Andorra,"
"AE:Asia/Dubai,"
"AF:Asia/Kabul,"
"AG:America/Antigua,"
"AI:America/Anguilla,"
"AL:Europe/Tirane,"
"AM:Asia/Yerevan,"
"AN:America/Curacao,"
"AO:Africa/Luanda,"
"AQ:Antarctica/South_Pole,"
"AR:America/Argentina/Buenos_Aires,"
"AS:Pacific/Pago_Pago,"
"AT:Europe/Vienna,"
"AU:Australia/Sydney,"
"AW:America/Aruba,"
"AX:Europe/Mariehamn,"
"AZ:Asia/Baku,"
"BA:Europe/Sarajevo,"
"BB:America/Barbados,"
"BD:Asia/Dhaka,"
"BE:Europe/Brussels,"
"BF:Africa/Ouagadougou,"
"BG:Europe/Sofia,"
"BH:Asia/Bahrain,"
"BI:Africa/Bujumbura,"
"BJ:Africa/Porto-Novo,"
"BM:Atlantic/Bermuda,"
"BN:Asia/Brunei,"
"BO:America/La_Paz,"
"BR:America/Sao_Paulo,"
"BS:America/Nassau,"
"BT:Asia/Thimphu,"
"BW:Africa/Gaborone,"
"BY:Europe/Minsk,"
"BZ:America/Belize,"
"CA:America/Toronto,"
"CC:Indian/Cocos,"
"CD:Africa/Kinshasa,"
"CF:Africa/Bangui,"
"CG:Africa/Brazzaville,"
"CH:Europe/Zurich,"
"CI:Africa/Abidjan,"
"CK:Pacific/Rarotonga,"
"CL:America/Santiago,"
"CM:Africa/Douala,"
"CN:Asia/Shanghai,"
"CO:America/Bogota,"
"CR:America/Costa_Rica,"
"CU:America/Havana,"
"CV:Atlantic/Cape_Verde,"
"CX:Indian/Christmas,"
"CY:Asia/Nicosia,"
"CZ:Europe/Prague,"
"DE:Europe/Berlin,"
"DJ:Africa/Djibouti,"
"DK:Europe/Copenhagen,"
"DM:America/Dominica,"
"DO:America/Santo_Domingo,"
"DZ:Africa/Algiers,"
"EC:America/Guayaquil,"
"EE:Europe/Tallinn,"
"EG:Africa/Cairo,"
"EH:Africa/El_Aaiun,"
"ER:Africa/Asmara,"
"ES:Europe/Madrid,"
"ET:Africa/Addis_Ababa,"
"FI:Europe/Helsinki,"
"FJ:Pacific/Fiji,"
"FK:Atlantic/Stanley,"
"FM:Pacific/Truk,"
"FO:Atlantic/Faroe,"
"FR:Europe/Paris,"
"GA:Africa/Libreville,"
"GB:Europe/London,"
"GD:America/Grenada,"
"GE:Asia/Tbilisi,"
"GF:America/Cayenne,"
"GG:Europe/Guernsey,"
"GH:Africa/Accra,"
"GI:Europe/Gibraltar,"
"GL:America/Godthab,"
"GM:Africa/Banjul,"
"GN:Africa/Conakry,"
"GP:America/Guadeloupe,"
"GQ:Africa/Malabo,"
"GR:Europe/Athens,"
"GS:Atlantic/South_Georgia,"
"GT:America/Guatemala,"
"GU:Pacific/Guam,"
"GW:Africa/Bissau,"
"GY:America/Guyana,"
"HK:Asia/Hong_Kong,"
"HN:America/Tegucigalpa,"
"HR:Europe/Zagreb,"
"HT:America/Port-au-Prince,"
"HU:Europe/Budapest,"
"ID:Asia/Jakarta,"
"IE:Europe/Dublin,"
"IL:Asia/Jerusalem,"
"IM:Europe/Isle_of_Man,"
"IN:Asia/Calcutta,"
"IO:Indian/Chagos,"
"IQ:Asia/Baghdad,"
"IR:Asia/Tehran,"
"IS:Atlantic/Reykjavik,"
"IT:Europe/Rome,"
"JE:Europe/Jersey,"
"JM:America/Jamaica,"
"JO:Asia/Amman,"
"JP:Asia/Tokyo,"
"KE:Africa/Nairobi,"
"KG:Asia/Bishkek,"
"KH:Asia/Phnom_Penh,"
"KI:Pacific/Enderbury,"
"KM:Indian/Comoro,"
"KN:America/St_Kitts,"
"KP:Asia/Pyongyang,"
"KR:Asia/Seoul,"
"KW:Asia/Kuwait,"
"KY:America/Cayman,"
"KZ:Asia/Almaty,"
"LA:Asia/Vientiane,"
"LB:Asia/Beirut,"
"LC:America/St_Lucia,"
"LI:Europe/Vaduz,"
"LK:Asia/Colombo,"
"LR:Africa/Monrovia,"
"LS:Africa/Maseru,"
"LT:Europe/Vilnius,"
"LU:Europe/Luxembourg,"
"LV:Europe/Riga,"
"LY:Africa/Tripoli,"
"MA:Africa/Casablanca,"
"MC:Europe/Monaco,"
"MD:Europe/Chisinau,"
"ME:Europe/Podgorica,"
"MG:Indian/Antananarivo,"
"MH:Pacific/Majuro,"
"MK:Europe/Skopje,"
"ML:Africa/Bamako,"
"MM:Asia/Rangoon,"
"MN:Asia/Hovd,"
"MO:Asia/Macau,"
"MP:Pacific/Saipan,"
"MQ:America/Martinique,"
"MR:Africa/Nouakchott,"
"MS:America/Montserrat,"
"MT:Europe/Malta,"
"MU:Indian/Mauritius,"
"MV:Indian/Maldives,"
"MW:Africa/Blantyre,"
"MX:America/Mexico_City,"
"MY:Asia/Kuala_Lumpur,"
"MZ:Africa/Maputo,"
"NA:Africa/Windhoek,"
"NC:Pacific/Noumea,"
"NE:Africa/Niamey,"
"NF:Pacific/Norfolk,"
"NG:Africa/Lagos,"
"NI:America/Managua,"
"NL:Europe/Amsterdam,"
"NO:Europe/Oslo,"
"NP:Asia/Katmandu,"
"NR:Pacific/Nauru,"
"NU:Pacific/Niue,"
"NZ:Pacific/Auckland,"
"OM:Asia/Muscat,"
"PA:America/Panama,"
"PE:America/Lima,"
"PF:Pacific/Tahiti,"
"PG:Pacific/Port_Moresby,"
"PH:Asia/Manila,"
"PK:Asia/Karachi,"
"PL:Europe/Warsaw,"
"PM:America/Miquelon,"
"PN:Pacific/Pitcairn,"
"PR:America/Puerto_Rico,"
"PS:Asia/Gaza,"
"PT:Europe/Lisbon,"
"PW:Pacific/Palau,"
"PY:America/Asuncion,"
"QA:Asia/Qatar,"
"RE:Indian/Reunion,"
"RO:Europe/Bucharest,"
"RS:Europe/Belgrade,"
"RU:Europe/Moscow,"
"RW:Africa/Kigali,"
"SA:Asia/Riyadh,"
"SB:Pacific/Guadalcanal,"
"SC:Indian/Mahe,"
"SD:Africa/Khartoum,"
"SE:Europe/Stockholm,"
"SG:Asia/Singapore,"
"SH:Atlantic/St_Helena,"
"SI:Europe/Ljubljana,"
"SJ:Atlantic/Jan_Mayen,"
"SK:Europe/Bratislava,"
"SL:Africa/Freetown,"
"SM:Europe/San_Marino,"
"SN:Africa/Dakar,"
"SO:Africa/Mogadishu,"
"SR:America/Paramaribo,"
"ST:Africa/Sao_Tome,"
"SV:America/El_Salvador,"
"SY:Asia/Damascus,"
"SZ:Africa/Mbabane,"
"TC:America/Grand_Turk,"
"TD:Africa/Ndjamena,"
"TF:Indian/Kerguelen,"
"TG:Africa/Lome,"
"TH:Asia/Bangkok,"
"TJ:Asia/Dushanbe,"
"TK:Pacific/Fakaofo,"
"TL:Asia/Dili,"
"TM:Asia/Ashgabat,"
"TN:Africa/Tunis,"
"TO:Pacific/Tongatapu,"
"TR:Europe/Istanbul,"
"TT:America/Port_of_Spain,"
"TV:Pacific/Funafuti,"
"TW:Asia/Taipei,"
"TZ:Africa/Dar_es_Salaam,"
"UA:Europe/Kiev,"
"UG:Africa/Kampala,"
"UM:Pacific/Midway,"
"US:America/New_York,"
"UY:America/Montevideo,"
"UZ:Asia/Samarkand,"
"VA:Europe/Vatican,"
"VC:America/St_Vincent,"
"VE:America/Caracas,"
"VG:America/Tortola,"
"VI:America/St_Thomas,"
"VN:Asia/Saigon,"
"VU:Pacific/Efate,"
"WF:Pacific/Wallis,"
"WS:Pacific/Apia,"
"YE:Asia/Aden,"
"YT:Indian/Mayotte,"
"ZA:Africa/Johannesburg,"
"ZM:Africa/Lusaka,"
"ZW:Africa/Harare";


static QMap<QString, QString> s_CountryGmtTimezoneMap;
static QMap<QString, QString> s_CountryTimezoneMap;
static QMap<QString, QString> s_GmtTimezoneMap;

static void LoadCountryGmtTimezone() {
    XUtils::LoadMap(s_ContryGmtTimezone, s_CountryGmtTimezoneMap);
}

static void LoadCountryTimezone() {
    XUtils::LoadMap(s_CountryTimezone, s_CountryTimezoneMap);
}

static void LoadGmtTimezone() {
    XUtils::LoadMap(s_GmtTimezone, s_GmtTimezoneMap);
}

namespace  XUtils{

QString StandTimezone(const QString &country, const QString &gmt) {
    LoadCountryGmtTimezone();
    LoadCountryTimezone();
    LoadGmtTimezone();
    //(MX&-7)
    QString countryGmt = QString("(%1&%2)").arg(country).arg(gmt);
    QString timezone = s_CountryGmtTimezoneMap[countryGmt];
    if(!timezone.isEmpty()) {
        return timezone;
    }

    timezone = s_CountryTimezoneMap[country];
    if(!timezone.isEmpty()) {
        return timezone;
    }

    timezone = s_GmtTimezoneMap[country];
    if(!timezone.isEmpty()) {
        return timezone;
    }

    return "Asia/Shanghai";
}

}
